SELECT BOARD_NO
    , BOARD_TITLE
    , BOARD_WRITER
    , ORIGIN_NAME
    , CHANGE_NAME
    , COUNT
    , TO_CHAR(CREATE_DATE, 'YYYY-MM-DD')  "CREATE_DATE"
FROM BOARD
WHERE STATUS = 'Y'
ORDER BY BOARD_NO DESC