-- C##mybatis / mybatis
-- 사용자 계정 추가 : CREATE USER 사용자이름 IDENTIFIED BY 비밀번호;
CREATE USER C##FESWORK IDENTIFIED BY FESWORK;

-- 권한 부여 : GRANT CONNECT, RESOURCE TO 사용자이름;
GRANT CONNECT, RESOURCE TO C##FESWORK;

-- 테이블스페이스 설정
ALTER USER C##FESWORK DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;