INSERT INTO RESERVATION (RESERVATION_NO,USERS_ID,RESERVATION_DATE,RESERVATION_STATUS)
VALUES (2, 'imij0126',SYSDATE,'y');

INSERT INTO RESERVATION (RESERVATION_NO,USERS_ID,RESERVATION_DATE,RESERVATION_STATUS)
VALUES (3, 'whdrns456',SYSDATE,'y');

INSERT INTO RESERVATION (RESERVATION_NO,USERS_ID,RESERVATION_DATE,RESERVATION_STATUS)
VALUES (4, 'JKW456',SYSDATE,'y');

INSERT INTO LUNCHBOX_RESERVATION (RESERVATION_NO,AMOUNT,LUNCHBOX_DETAILS)
VALUES (2,1,'3ø');

INSERT INTO LUNCHBOX_RESERVATION (RESERVATION_NO,AMOUNT,LUNCHBOX_DETAILS)
VALUES (3,2,'5ø');

INSERT INTO LUNCHBOX_RESERVATION (RESERVATION_NO,AMOUNT,LUNCHBOX_DETAILS)
VALUES (4,3,'7ø');

COMMIT;


delete FROM LUNCHBOX_RESERVATION 
WHERE RESERVATION_NO = 24;