-- Create JOB_CODE table
DROP TABLE JOB_CODE;
DROP TABLE DEPT;
DROP TABLE EMPLOYEE;
drop table post;
drop table reply;
drop table menu;
drop table notice;
drop table users;

CREATE TABLE JOB_CODE (
    JOB_CODE VARCHAR2(9) NOT NULL,
    JOB_NAME VARCHAR2(215) NOT NULL,
    PRIMARY KEY (JOB_CODE)
);

-- Create DEPT table
CREATE TABLE DEPT (
    DEPT_CODE VARCHAR2(9) NOT NULL,
    DEPT_NAME VARCHAR2(215) NOT NULL,
    PRIMARY KEY (DEPT_CODE)
);

-- Create EMPLOYEE table
CREATE TABLE EMPLOYEE (
    USERS_ID VARCHAR2(20) NOT NULL,
    DEPT_CODE VARCHAR2(9) NOT NULL,
    JOB_CODE VARCHAR2(9) NOT NULL,
    EMPLOYEE_TYPE VARCHAR2(19) NOT NULL,
    SALARY NUMBER NOT NULL,
    PRIMARY KEY (USERS_ID),
    FOREIGN KEY (DEPT_CODE) REFERENCES DEPT(DEPT_CODE),
    FOREIGN KEY (JOB_CODE) REFERENCES JOB_CODE(JOB_CODE)
);

drop table job_code;

INSERT INTO JOB_CODE (JOB_CODE, JOB_NAME) VALUES ('Manager','관리자');
INSERT INTO JOB_CODE (JOB_CODE, JOB_NAME) VALUES ('CEO','사장');
INSERT INTO JOB_CODE (JOB_CODE, JOB_NAME) VALUES ('Chef','주방장');
INSERT INTO JOB_CODE (JOB_CODE, JOB_NAME) VALUES ('Guard','가드');

INSERT INTO DEPT (DEPT_CODE, DEPT_NAME) VALUES ('M1', 'Management');
INSERT INTO DEPT (DEPT_CODE, DEPT_NAME) VALUES ('A1', 'Administration');
INSERT INTO DEPT (DEPT_CODE, DEPT_NAME) VALUES ('C1', 'Culinary');
INSERT INTO DEPT (DEPT_CODE, DEPT_NAME) VALUES ('G1', 'Guarding');

-- 올바른 JOB_CODE 값을 사용하도록 수정
INSERT INTO EMPLOYEE(USERS_ID, DEPT_CODE, JOB_CODE, EMPLOYEE_TYPE, SALARY) VALUES
('imij0126', 'M1', 'Manager', 'X', 2500000);

INSERT INTO EMPLOYEE(USERS_ID, DEPT_CODE, JOB_CODE, EMPLOYEE_TYPE, SALARY) VALUES
('whdrns456', 'A1', 'CEO', 'A', 10000000);

INSERT INTO EMPLOYEE(USERS_ID, DEPT_CODE, JOB_CODE, EMPLOYEE_TYPE, SALARY) VALUES
('ymw0011', 'C1', 'Chef', 'C', 50000000);

INSERT INTO EMPLOYEE(USERS_ID, DEPT_CODE, JOB_CODE, EMPLOYEE_TYPE, SALARY) VALUES
('jkw0011', 'G1', 'Guard', 'X', 3000000);

commit;

UPDATE USERS
SET USERS_NAME = '김수창',
    EMAIL = 'imij0126@naver.com'
WHERE USERS_ID = 'imij0126';

UPDATE EMPLOYEE
SET JOB_CODE = 'Manager'
WHERE USERS_ID = 'imij0126';

COMMIT;
ROLLBACK;

delete users
where users.users_id = 'cjk0011';

		SELECT U.USERS_NAME, U.EMAIL, J.JOB_NAME
		FROM USERS U
		JOIN EMPLOYEE E ON E.USERS_ID = U.USERS_ID
		JOIN JOB_CODE J ON J.JOB_CODE = E.JOB_CODE;
