INSERT INTO RESERVATION (RESERVATION_NO, USERS_ID, RESERVATION_DATE, RESERVATION_STATUS)
VALUES (RESERVATION_SEQ.NEXTVAL, 'imij0126', SYSDATE, 'y');

INSERT INTO RESERVATION (RESERVATION_NO, USERS_ID, RESERVATION_DATE, RESERVATION_STATUS)
VALUES (RESERVATION_SEQ.NEXTVAL, 'whdrns456', SYSDATE, 'y');

INSERT INTO RESERVATION (RESERVATION_NO, USERS_ID, RESERVATION_DATE, RESERVATION_STATUS)
VALUES (RESERVATION_SEQ.NEXTVAL, 'JKW456', SYSDATE, 'y');

INSERT INTO RESERVATION (RESERVATION_NO, USERS_ID, RESERVATION_DATE, RESERVATION_STATUS)
VALUES (RESERVATION_SEQ.NEXTVAL, 'YMW456', SYSDATE, 'y');

INSERT INTO TABLE_RESERVATION (RESERVATION_NO,TABLE_NO)
VALUES (22, 'A-2');

INSERT INTO TABLE_RESERVATION (RESERVATION_NO,TABLE_NO)
VALUES (23, 'A-3');

INSERT INTO TABLE_RESERVATION (RESERVATION_NO,TABLE_NO)
VALUES (24, 'A-4');

INSERT INTO TABLE_RESERVATION (RESERVATION_NO,TABLE_NO)
VALUES (25, 'A-5');

INSERT INTO LUNCHBOX_RESERVATION (RESERVATION_NO,AMOUNT,LUNCHBOX_DETAILS)
VALUES (22,2,'3Ã¸');

INSERT INTO LUNCHBOX_RESERVATION (RESERVATION_NO,AMOUNT,LUNCHBOX_DETAILS)
VALUES (1,1,'5Ã¸');

INSERT INTO LUNCHBOX_RESERVATION (RESERVATION_NO,AMOUNT,LUNCHBOX_DETAILS)
VALUES (23,2,'7Ã¸');

INSERT INTO LUNCHBOX_RESERVATION (RESERVATION_NO,AMOUNT,LUNCHBOX_DETAILS)
VALUES (24,2,'3Ã¸');

CREATE TABLE LUNCHBOX_RESERVATION (
    RESERVATION_NO NUMBER PRIMARY KEY, -- ¿¹¾à ID
    AMOUNT NUMBER NOT NULL,            -- ¼ö·®
    LUNCHBOX_DETAILS VARCHAR2(5) CHECK(LUNCHBOX_DETAILS IN('3Ã¸', '5Ã¸', '7Ã¸')), -- µµ½Ã¶ô ¼¼ºÎ Á¤º¸
    FOREIGN KEY (RESERVATION_NO) REFERENCES RESERVATION(RESERVATION_NO)
);
DROP TABLE LUNCHBOX_RESERVATION;

commit;
ROLLBACK;

	    		SELECT R.RESERVATION_NO, U.USERS_NAME, T.TABLE_NO, TO_CHAR(R.RESERVATION_DATE, 'HH24:MI:SS')
		FROM RESERVATION R
		JOIN USERS U ON U.USERS_ID = R.USERS_ID
		JOIN TABLE_RESERVATION T ON R.RESERVATION_NO = T.RESERVATION_NO
		WHERE RESERVATION_STATUS = 'y'
		ORDER BY R.RESERVATION_NO ASC;
        
SELECT L.RESERVATION_NO,U.USERS_NAME,L.LUNCHBOX_DETAILS
FROM LUNCHBOX_RESERVATION L
JOIN RESERVATION R ON R.RESERVATION_NO = L.RESERVATION_NO 
JOIN USERS U ON U.USERS_ID = R.USERS_ID; 