
CREATE TABLE USERS(
USERS_ID VARCHAR2(20) NOT NULL UNIQUE,
USERS_PASSWORD VARCHAR2(100) NOT NULL,
USERS_NAME VARCHAR2(30) NOT NULL,
EMAIL VARCHAR2(30) NOT NULL UNIQUE,
JOIN_DATE DATE DEFAULT SYSDATE NOT NULL,
WITHDRAWAL_DATE DATE,
USERS_STATE VARCHAR2(1) CHECK (USERS_STATE IN ('y', 'n')) NOT NULL ,
USERS_TYPE VARCHAR2(9) DEFAULT '고객' NOT NULL,
CONSTRAINT chk_user_type CHECK (USERS_TYPE IN ('고객', '직원'))
);

InSERT INTO USERS VALUES(
'imij0126' ,
'imij6414',
'김인창' ,
'imij@naver.com'
,sysdate, null, 'y', '직원'
);

InSERT INTO USERS VALUES(
'JKW456' ,
'damgarak123!',
'조건웅' ,
'JKW456@naver.com'
,sysdate, null, 'y', '직원'
);

InSERT INTO USERS VALUES(
'YMW456' ,
'damgarak123!',
'양민욱' ,
'YMW456@naver.com'
,sysdate, null, 'y', '직원'
);

INSERT INTO EMPLOYEE (
    USERS_ID, EMPLOYEE_NAME, PHONE, ADDRESS, DEPT_CODE, JOB_CODE, SALARY,EMPLOYEE_TYPE
) VALUES ('imij0126', '김인창', '010-8888-0780','서울시 동작구 사당동', 'D01', 'J02',1000000,'직원');

INSERT INTO EMPLOYEE (
    USERS_ID, EMPLOYEE_NAME, PHONE, ADDRESS, DEPT_CODE, JOB_CODE, SALARY,EMPLOYEE_TYPE
) VALUES ('JKW456', '조건웅', '010-8888-4444','춘천시 춘천구 닭갈비', 'D01', 'J02',1000000,'직원');

INSERT INTO EMPLOYEE (
    USERS_ID, EMPLOYEE_NAME, PHONE, ADDRESS, DEPT_CODE, JOB_CODE, SALARY,EMPLOYEE_TYPE
) VALUES ('YMW456', '양민욱', '010-2222-4444','서울시 어딘가 어디구', 'D01', 'J02',1000000,'직원');

UPDATE USERS
   SET USERS_STATE = 'y'
 WHERE USERS_NAME = '최종군';

commit;

delete from employee where employee_name = '양민욱';
---

---

CREATE TABLE MENU_CATEGORY (
MENU_CATEGORY_CODE VARCHAR2(2) NOT NULL,
MENU_CATEGORY_NAME VARCHAR2(15) NOT NULL,
PRIMARY KEY (MENU_CATEGORY_CODE)
);
INSERT INTO MENU_CATEGORY (MENU_CATEGORY_CODE, MENU_CATEGORY_NAME)
VALUES ('01', '구이류');

INSERT INTO MENU_CATEGORY (MENU_CATEGORY_CODE, MENU_CATEGORY_NAME)
VALUES ('02', '국물류');

INSERT INTO MENU_CATEGORY (MENU_CATEGORY_CODE, MENU_CATEGORY_NAME)
VALUES ('03', '찜류');

INSERT INTO MENU_CATEGORY (MENU_CATEGORY_CODE, MENU_CATEGORY_NAME)
VALUES ('04', '볶음류');

INSERT INTO MENU_CATEGORY (MENU_CATEGORY_CODE, MENU_CATEGORY_NAME)
VALUES ('05', '후식');

INSERT INTO MENU_CATEGORY (MENU_CATEGORY_CODE, MENU_CATEGORY_NAME)
VALUES ('06', '반찬류');

CREATE TABLE MENU (
MENU_NO NUMBER NOT NULL,
MENU_NAME VARCHAR2(50) NULL,
PRICE NUMBER DEFAULT 0 NOT NULL,
MENU_TYPE VARCHAR2(2) NULL CHECK (MENU_TYPE IN ('r','l','a')),
MENU_IMAGE VARCHAR2(200) NULL,
MENU_DESCRIPTION VARCHAR2(150) NULL,
CALORIE NUMBER NOT NULL,
MENU_CATEGORY_CODE VARCHAR2(2 ) NOT NULL,
MENU_COUNT NUMBER DEFAULT 0,
PRIMARY KEY (MENU_NO),
FOREIGN KEY (MENU_CATEGORY_CODE)
REFERENCES MENU_CATEGORY (MENU_CATEGORY_CODE)
);

---------------------------------구이류------------------------------------------
INSERT INTO MENU (MENU_NO, MENU_NAME, PRICE, MENU_TYPE, MENU_IMAGE, MENU_DESCRIPTION, CALORIE, MENU_CATEGORY_CODE, MENU_COUNT)
VALUES (1001, '삼겹살 구이', 14000, 'a', 'menu_01_1001.jpg', '노릇노릇하게 구운 한돈 삼겹살', 650, '01', 50);

INSERT INTO MENU (MENU_NO, MENU_NAME, PRICE, MENU_TYPE, MENU_IMAGE, MENU_DESCRIPTION, CALORIE, MENU_CATEGORY_CODE, MENU_COUNT)
VALUES (1002, '고등어 구이', 13000, 'a', 'menu_01_1002.jpg', '방금까지 살아있던 고등어 구이', 300, '01', 5);

INSERT INTO MENU (MENU_NO, MENU_NAME, PRICE, MENU_TYPE, MENU_IMAGE, MENU_DESCRIPTION, CALORIE, MENU_CATEGORY_CODE, MENU_COUNT)
VALUES (1003, '훈제 가슴살', 8000, 'a', 'menu_01_1003.jpg', '다이어터를 위한 훈제 가슴살', 250, '01', 2000);
---------------------------------구이류------------------------------------------

- --------------------------------국물류-------------------------------
INSERT INTO MENU (MENU_NO, MENU_NAME, PRICE, MENU_TYPE, MENU_IMAGE, MENU_DESCRIPTION, CALORIE, MENU_CATEGORY_CODE, MENU_COUNT)
VALUES (2001, '김치찌개', 9000, 'r', 'menu_02_2001', '김치를 끓는 물에 넣어 고기와 여러 재료들을 넣은 국물요리', 450, '02', 70);

INSERT INTO MENU (MENU_NO, MENU_NAME, PRICE, MENU_TYPE, MENU_IMAGE, MENU_DESCRIPTION, CALORIE, MENU_CATEGORY_CODE, MENU_COUNT)
VALUES (2002, '순두부찌개', 8500, 'l', 'menu_02_2002', '순두부를 가득 넣고 양념을 한 국물요리', 450, '02', 60);

INSERT INTO MENU (MENU_NO, MENU_NAME, PRICE, MENU_TYPE, MENU_IMAGE, MENU_DESCRIPTION, CALORIE, MENU_CATEGORY_CODE, MENU_COUNT)
VALUES (2003, '된장찌개', 8000, 'l', 'menu_02_2003', '된장을 넣고 두부를 넣어서 구수한 맛을 낸 국물요리', 300, '02', 50);

INSERT INTO MENU (MENU_NO, MENU_NAME, PRICE, MENU_TYPE, MENU_IMAGE, MENU_DESCRIPTION, CALORIE, MENU_CATEGORY_CODE, MENU_COUNT)
VALUES (2004, '부대찌개', 12000, 'r', 'menu_02_2004', '여러가지 햄들을 넣고 라면사리를 넣은 국물요리', 600, '02', 80);

INSERT INTO MENU (MENU_NO, MENU_NAME, PRICE, MENU_TYPE, MENU_IMAGE, MENU_DESCRIPTION, CALORIE, MENU_CATEGORY_CODE, MENU_COUNT)
VALUES (2005, '동태찌개', 11000, 'r', 'menu_02_2005', '동태와 여러가지 야채를 넣어 시원한 맛을 낸 국물요리', 550, '02', 55);

INSERT INTO MENU (MENU_NO, MENU_NAME, PRICE, MENU_TYPE, MENU_IMAGE, MENU_DESCRIPTION, CALORIE, MENU_CATEGORY_CODE, MENU_COUNT)
VALUES (2006, '삼계탕', 12000, 'r', 'menu_02_2006', '닭을 한 그릇에 넣어 인삼과 같이 요리한 국물요리', 600, '02', 90);

INSERT INTO MENU (MENU_NO, MENU_NAME, PRICE, MENU_TYPE, MENU_IMAGE, MENU_DESCRIPTION, CALORIE, MENU_CATEGORY_CODE, MENU_COUNT)
VALUES (2007, '순대국', 9000, 'l', 'menu_02_2007', '순대를 넣고 요리한 국물요리', 600, '02', 95);

INSERT INTO MENU (MENU_NO, MENU_NAME, PRICE, MENU_TYPE, MENU_IMAGE, MENU_DESCRIPTION, CALORIE, MENU_CATEGORY_CODE, MENU_COUNT)
VALUES (2008, '육개장', 9000, 'l', 'menu_02_2008', '소고기와 고사리 등 여러 야채를 넣고 끓인 국물요리', 480, '02', 83);

INSERT INTO MENU (MENU_NO, MENU_NAME, PRICE, MENU_TYPE, MENU_IMAGE, MENU_DESCRIPTION, CALORIE, MENU_CATEGORY_CODE, MENU_COUNT)
VALUES (2009, '갈비탕', 12000, 'l', 'menu_02_2009', '갈비를 넣고 시원하게 끓인 국물요리', 630, '02', 73);

INSERT INTO MENU (MENU_NO, MENU_NAME, PRICE, MENU_TYPE, MENU_IMAGE, MENU_DESCRIPTION, CALORIE, MENU_CATEGORY_CODE, MENU_COUNT)
VALUES (2010, '매운탕', 11000, 'r', 'menu_02_2010', '생선과 해물을 넣고 여러 야채를 넣고 맵게 끓인 국물요리', 700, '02', 80);
---------------------------------------------국물류-------------------------------

- --------------------------------------------찜---------------------------------------------------------
INSERT INTO MENU (MENU_NO, MENU_NAME, PRICE, MENU_TYPE, MENU_IMAGE, MENU_DESCRIPTION, CALORIE, MENU_CATEGORY_CODE, MENU_COUNT)
VALUES (3001, '갈비찜', 50000, 'r', 'menu_03_3001.jpg', '맛있는 갈비찜', 2000, '03', 5);
INSERT INTO MENU (MENU_NO, MENU_NAME, PRICE, MENU_TYPE, MENU_IMAGE, MENU_DESCRIPTION, CALORIE, MENU_CATEGORY_CODE, MENU_COUNT)
VALUES (3002, '김치찜', 50000, 'r', 'menu_03_3002.jpg', '맛있는 김치찜', 3000, '03', 2);
INSERT INTO MENU (MENU_NO, MENU_NAME, PRICE, MENU_TYPE, MENU_IMAGE, MENU_DESCRIPTION, CALORIE, MENU_CATEGORY_CODE, MENU_COUNT)
VALUES (3003, '해물찜', 50000, 'r', 'menu_03_3003.jpg', '맛있는 갈비찜', 100, '03', 21);
---------------------------------------------찜---------------------------------------------------------
- ----------------------------------------------볶음------------------------------------------------------
INSERT INTO MENU (MENU_NO, MENU_NAME, PRICE, MENU_TYPE, MENU_IMAGE, MENU_DESCRIPTION, CALORIE, MENU_CATEGORY_CODE, MENU_COUNT)
VALUES (4001, '낚지볶음', 210000, 'r', 'menu_04_4001.jpg', '맛있는 낚지볶음', 2, '04', 80);
INSERT INTO MENU (MENU_NO, MENU_NAME, PRICE, MENU_TYPE, MENU_IMAGE, MENU_DESCRIPTION, CALORIE, MENU_CATEGORY_CODE, MENU_COUNT)
VALUES (4002, '소고기 버섯볶음', 220000, 'r', 'menu_04_4002.jpg', '맛있는 소고기 버섯볶음', 60, '04', 60);
INSERT INTO MENU (MENU_NO, MENU_NAME, PRICE, MENU_TYPE, MENU_IMAGE, MENU_DESCRIPTION, CALORIE, MENU_CATEGORY_CODE, MENU_COUNT)
VALUES (4003, '제육볶음', 230000, 'r', 'menu_04_4003.jpg', '맛있는 제육볶음', 900, '04', 1);
-----------------------------------------------볶음------------------------------------------------------
- ------------------------------------------후식---------------------------------------------------------
INSERT INTO MENU (MENU_NO, MENU_NAME, PRICE, MENU_TYPE, MENU_IMAGE, MENU_DESCRIPTION, CALORIE, MENU_CATEGORY_CODE, MENU_COUNT)
VALUES (5001, '인절미', 3000,'r', 'MENU_05_5001.jpg', '부드러운 인절미과 달톰한꿀의 조합', 340, '05', 30);

INSERT INTO MENU (MENU_NO, MENU_NAME, PRICE, MENU_TYPE, MENU_IMAGE, MENU_DESCRIPTION, CALORIE, MENU_CATEGORY_CODE, MENU_COUNT)
VALUES (5002, '식혜', 2400, 'l', 'MENU_05_5002.jpg', '작게 썰어 말린 대추를올린 달콤한 식혜', 240, '05', 50);

INSERT INTO MENU (MENU_NO, MENU_NAME, PRICE, MENU_TYPE, MENU_IMAGE, MENU_DESCRIPTION, CALORIE, MENU_CATEGORY_CODE, MENU_COUNT)
VALUES (5003, '곳감수정과', 2500, 'a', 'MENU_05_5003.jpg', '잘말린 곳감을 작게 썰어 함께즐기는 새콤달콤한 곳감수정과', 200, '05', 30);

INSERT INTO MENU (MENU_NO, MENU_NAME, PRICE, MENU_TYPE, MENU_IMAGE, MENU_DESCRIPTION, CALORIE, MENU_CATEGORY_CODE, MENU_COUNT)
VALUES (5004, '양갱', 2500, 'a', 'MENU_05_5004', '다양한 맛을 즐기수 있는 전통적인 양갱', 250, '05', 60);

INSERT INTO MENU (MENU_NO, MENU_NAME, PRICE, MENU_TYPE, MENU_IMAGE, MENU_DESCRIPTION, CALORIE, MENU_CATEGORY_CODE, MENU_COUNT)
VALUES (5005, '오메기떡', 3000, 'a', 'MENU_05_5005.jpeg', '단백하고 다양한 토핑으로 같이 즐기수있는 전통적인 현대 떡', 150, '05', 20);
-------------------------------------------후식---------------------------------------------------------

- -------------------------------------------반찬류------------------------------------
INSERT INTO MENU (MENU_NO, MENU_NAME, PRICE, MENU_TYPE, MENU_IMAGE, MENU_DESCRIPTION, CALORIE, MENU_CATEGORY_CODE, MENU_COUNT)
VALUES (6001, '한우오이볶음', 4000,'r', 'MENU_06_6001.jpg', '단자스런운 한우고기랑 상큼한 오이의 만남', 140, '06', 80);

INSERT INTO MENU (MENU_NO, MENU_NAME, PRICE, MENU_TYPE, MENU_IMAGE, MENU_DESCRIPTION, CALORIE, MENU_CATEGORY_CODE, MENU_COUNT)
VALUES (6002, '장조림.', 3400, 'l', 'MENU_06_6002.jpg', '남녀노소 누구나 좋아하는 장조림', 110, '06', 50);

INSERT INTO MENU (MENU_NO, MENU_NAME, PRICE, MENU_TYPE, MENU_IMAGE, MENU_DESCRIPTION, CALORIE, MENU_CATEGORY_CODE, MENU_COUNT)
VALUES (6003, '오징어채', 2500, 'a', 'MENU_06_6003.jpg', '매콤하고 부드러운 국민반찬 오징어채', 210, '06', 40);

INSERT INTO MENU (MENU_NO, MENU_NAME, PRICE, MENU_TYPE, MENU_IMAGE, MENU_DESCRIPTION, CALORIE, MENU_CATEGORY_CODE, MENU_COUNT)
VALUES (6004, '계란말이', 2500, 'a', 'MENU_06_6004.jpg', '부드럽고 짭짭한 국민 밥반찬 계란말이', 250, '06', 60);

INSERT INTO MENU (MENU_NO, MENU_NAME, PRICE, MENU_TYPE, MENU_IMAGE, MENU_DESCRIPTION, CALORIE, MENU_CATEGORY_CODE, MENU_COUNT)
VALUES (6005, '느타리벗섯볶음', 3000, 'a', 'MENU_06_6005.jpg', '짭쫄한 밥반찬', 150, '06', 20);
-----------------------------------반찬류----------------------------------------------------

- -------------------------추천 메뉴------------------------------------------------------------
INSERT INTO SUGGEST_MENU (MENU_NO, SUGGEST_STATUS)
VALUES (1003, 'y');

INSERT INTO SUGGEST_MENU (MENU_NO, SUGGEST_STATUS)
VALUES (2008, 'y');

INSERT INTO SUGGEST_MENU (MENU_NO, SUGGEST_STATUS)
VALUES (3001, 'y');

INSERT INTO SUGGEST_MENU (MENU_NO, SUGGEST_STATUS)
VALUES (4002, 'y');

INSERT INTO SUGGEST_MENU (MENU_NO, SUGGEST_STATUS)
VALUES (5005, 'y');
--------------------------추천 메뉴------------------------------------------------------------

CREATE TABLE SUGGEST_MENU (
MENU_NO NUMBER NOT NULL,
SUGGEST_STATUS VARCHAR2(1) NOT NULL CHECK (SUGGEST_STATUS IN ('y','n')),
PRIMARY KEY (MENU_NO),
FOREIGN KEY (MENU_NO)
REFERENCES MENU (MENU_NO)
);

commit;
rollback;

DROP TABLE **USERS**;

CREATE TABLE USERS(
USERS_ID VARCHAR2(20) NOT NULL UNIQUE,
USERS_PASSWORD VARCHAR2(100) NOT NULL,
USERS_NAME VARCHAR2(30) NOT NULL,
EMAIL VARCHAR2(30) NOT NULL UNIQUE,
JOIN_DATE DATE DEFAULT SYSDATE NOT NULL,
WITHDRAWAL_DATE DATE,
USERS_STATE VARCHAR2(1) CHECK (USERS_STATE IN ('y', 'n')) NOT NULL ,
USERS_TYPE VARCHAR2(9) DEFAULT '고객' NOT NULL,
CONSTRAINT chk_user_type CHECK (USERS_TYPE IN ('고객', '직원'))
);

InSERT INTO USERS VALUES(
'whdrns456' ,
'damgarak123!',
'최종군' ,
'whdrns456@naver.com'
,sysdate, null, 'n', '직원'
);

---

---

CREATE TABLE MENU_CATEGORY (
MENU_CATEGORY_CODE VARCHAR2(2) NOT NULL,
MENU_CATEGORY_NAME VARCHAR2(15) NOT NULL,
PRIMARY KEY (MENU_CATEGORY_CODE)
);
INSERT INTO MENU_CATEGORY (MENU_CATEGORY_CODE, MENU_CATEGORY_NAME)
VALUES ('01', '구이류');

INSERT INTO MENU_CATEGORY (MENU_CATEGORY_CODE, MENU_CATEGORY_NAME)
VALUES ('02', '국물류');

INSERT INTO MENU_CATEGORY (MENU_CATEGORY_CODE, MENU_CATEGORY_NAME)
VALUES ('03', '찜류');

INSERT INTO MENU_CATEGORY (MENU_CATEGORY_CODE, MENU_CATEGORY_NAME)
VALUES ('04', '볶음류');

INSERT INTO MENU_CATEGORY (MENU_CATEGORY_CODE, MENU_CATEGORY_NAME)
VALUES ('05', '후식');

INSERT INTO MENU_CATEGORY (MENU_CATEGORY_CODE, MENU_CATEGORY_NAME)
VALUES ('06', '반찬류');

CREATE TABLE MENU (
MENU_NO NUMBER NOT NULL,
MENU_NAME VARCHAR2(50) NULL,
PRICE NUMBER DEFAULT 0 NOT NULL,
MENU_TYPE VARCHAR2(2) NULL CHECK (MENU_TYPE IN ('r','l','a')),
MENU_IMAGE VARCHAR2(200) NULL,
MENU_DESCRIPTION VARCHAR2(150) NULL,
CALORIE NUMBER NOT NULL,
MENU_CATEGORY_CODE VARCHAR2(2 ) NOT NULL,
MENU_COUNT NUMBER DEFAULT 0,
PRIMARY KEY (MENU_NO),
FOREIGN KEY (MENU_CATEGORY_CODE)
REFERENCES MENU_CATEGORY (MENU_CATEGORY_CODE)
);

---------------------------------구이류------------------------------------------
INSERT INTO MENU (MENU_NO, MENU_NAME, PRICE, MENU_TYPE, MENU_IMAGE, MENU_DESCRIPTION, CALORIE, MENU_CATEGORY_CODE, MENU_COUNT)
VALUES (1001, '삼겹살 구이', 14000, 'a', 'menu_01_1001.jpg', '노릇노릇하게 구운 한돈 삼겹살', 650, '01', 50);

INSERT INTO MENU (MENU_NO, MENU_NAME, PRICE, MENU_TYPE, MENU_IMAGE, MENU_DESCRIPTION, CALORIE, MENU_CATEGORY_CODE, MENU_COUNT)
VALUES (1002, '고등어 구이', 13000, 'a', 'menu_01_1002.jpg', '방금까지 살아있던 고등어 구이', 300, '01', 5);

INSERT INTO MENU (MENU_NO, MENU_NAME, PRICE, MENU_TYPE, MENU_IMAGE, MENU_DESCRIPTION, CALORIE, MENU_CATEGORY_CODE, MENU_COUNT)
VALUES (1003, '훈제 가슴살', 8000, 'a', 'menu_01_1003.jpg', '다이어터를 위한 훈제 가슴살', 250, '01', 2000);
---------------------------------구이류------------------------------------------

- --------------------------------국물류-------------------------------
INSERT INTO MENU (MENU_NO, MENU_NAME, PRICE, MENU_TYPE, MENU_IMAGE, MENU_DESCRIPTION, CALORIE, MENU_CATEGORY_CODE, MENU_COUNT)
VALUES (2001, '김치찌개', 9000, 'r', 'menu_02_2001', '김치를 끓는 물에 넣어 고기와 여러 재료들을 넣은 국물요리', 450, '02', 70);

INSERT INTO MENU (MENU_NO, MENU_NAME, PRICE, MENU_TYPE, MENU_IMAGE, MENU_DESCRIPTION, CALORIE, MENU_CATEGORY_CODE, MENU_COUNT)
VALUES (2002, '순두부찌개', 8500, 'l', 'menu_02_2002', '순두부를 가득 넣고 양념을 한 국물요리', 450, '02', 60);

INSERT INTO MENU (MENU_NO, MENU_NAME, PRICE, MENU_TYPE, MENU_IMAGE, MENU_DESCRIPTION, CALORIE, MENU_CATEGORY_CODE, MENU_COUNT)
VALUES (2003, '된장찌개', 8000, 'l', 'menu_02_2003', '된장을 넣고 두부를 넣어서 구수한 맛을 낸 국물요리', 300, '02', 50);

INSERT INTO MENU (MENU_NO, MENU_NAME, PRICE, MENU_TYPE, MENU_IMAGE, MENU_DESCRIPTION, CALORIE, MENU_CATEGORY_CODE, MENU_COUNT)
VALUES (2004, '부대찌개', 12000, 'r', 'menu_02_2004', '여러가지 햄들을 넣고 라면사리를 넣은 국물요리', 600, '02', 80);

INSERT INTO MENU (MENU_NO, MENU_NAME, PRICE, MENU_TYPE, MENU_IMAGE, MENU_DESCRIPTION, CALORIE, MENU_CATEGORY_CODE, MENU_COUNT)
VALUES (2005, '동태찌개', 11000, 'r', 'menu_02_2005', '동태와 여러가지 야채를 넣어 시원한 맛을 낸 국물요리', 550, '02', 55);

INSERT INTO MENU (MENU_NO, MENU_NAME, PRICE, MENU_TYPE, MENU_IMAGE, MENU_DESCRIPTION, CALORIE, MENU_CATEGORY_CODE, MENU_COUNT)
VALUES (2006, '삼계탕', 12000, 'r', 'menu_02_2006', '닭을 한 그릇에 넣어 인삼과 같이 요리한 국물요리', 600, '02', 90);

INSERT INTO MENU (MENU_NO, MENU_NAME, PRICE, MENU_TYPE, MENU_IMAGE, MENU_DESCRIPTION, CALORIE, MENU_CATEGORY_CODE, MENU_COUNT)
VALUES (2007, '순대국', 9000, 'l', 'menu_02_2007', '순대를 넣고 요리한 국물요리', 600, '02', 95);

INSERT INTO MENU (MENU_NO, MENU_NAME, PRICE, MENU_TYPE, MENU_IMAGE, MENU_DESCRIPTION, CALORIE, MENU_CATEGORY_CODE, MENU_COUNT)
VALUES (2008, '육개장', 9000, 'l', 'menu_02_2008', '소고기와 고사리 등 여러 야채를 넣고 끓인 국물요리', 480, '02', 83);

INSERT INTO MENU (MENU_NO, MENU_NAME, PRICE, MENU_TYPE, MENU_IMAGE, MENU_DESCRIPTION, CALORIE, MENU_CATEGORY_CODE, MENU_COUNT)
VALUES (2009, '갈비탕', 12000, 'l', 'menu_02_2009', '갈비를 넣고 시원하게 끓인 국물요리', 630, '02', 73);

INSERT INTO MENU (MENU_NO, MENU_NAME, PRICE, MENU_TYPE, MENU_IMAGE, MENU_DESCRIPTION, CALORIE, MENU_CATEGORY_CODE, MENU_COUNT)
VALUES (2010, '매운탕', 11000, 'r', 'menu_02_2010', '생선과 해물을 넣고 여러 야채를 넣고 맵게 끓인 국물요리', 700, '02', 80);
---------------------------------------------국물류-------------------------------

- --------------------------------------------찜---------------------------------------------------------
INSERT INTO MENU (MENU_NO, MENU_NAME, PRICE, MENU_TYPE, MENU_IMAGE, MENU_DESCRIPTION, CALORIE, MENU_CATEGORY_CODE, MENU_COUNT)
VALUES (3001, '갈비찜', 50000, 'r', 'menu_03_3001.jpg', '맛있는 갈비찜', 2000, '03', 5);
INSERT INTO MENU (MENU_NO, MENU_NAME, PRICE, MENU_TYPE, MENU_IMAGE, MENU_DESCRIPTION, CALORIE, MENU_CATEGORY_CODE, MENU_COUNT)
VALUES (3002, '김치찜', 50000, 'r', 'menu_03_3002.jpg', '맛있는 김치찜', 3000, '03', 2);
INSERT INTO MENU (MENU_NO, MENU_NAME, PRICE, MENU_TYPE, MENU_IMAGE, MENU_DESCRIPTION, CALORIE, MENU_CATEGORY_CODE, MENU_COUNT)
VALUES (3003, '해물찜', 50000, 'r', 'menu_03_3003.jpg', '맛있는 갈비찜', 100, '03', 21);
---------------------------------------------찜---------------------------------------------------------
- ----------------------------------------------볶음------------------------------------------------------
INSERT INTO MENU (MENU_NO, MENU_NAME, PRICE, MENU_TYPE, MENU_IMAGE, MENU_DESCRIPTION, CALORIE, MENU_CATEGORY_CODE, MENU_COUNT)
VALUES (4001, '낚지볶음', 210000, 'r', 'menu_04_4001.jpg', '맛있는 낚지볶음', 2, '04', 80);
INSERT INTO MENU (MENU_NO, MENU_NAME, PRICE, MENU_TYPE, MENU_IMAGE, MENU_DESCRIPTION, CALORIE, MENU_CATEGORY_CODE, MENU_COUNT)
VALUES (4002, '소고기 버섯볶음', 220000, 'r', 'menu_04_4002.jpg', '맛있는 소고기 버섯볶음', 60, '04', 60);
INSERT INTO MENU (MENU_NO, MENU_NAME, PRICE, MENU_TYPE, MENU_IMAGE, MENU_DESCRIPTION, CALORIE, MENU_CATEGORY_CODE, MENU_COUNT)
VALUES (4003, '제육볶음', 230000, 'r', 'menu_04_4003.jpg', '맛있는 제육볶음', 900, '04', 1);
-----------------------------------------------볶음------------------------------------------------------
- ------------------------------------------후식---------------------------------------------------------
INSERT INTO MENU (MENU_NO, MENU_NAME, PRICE, MENU_TYPE, MENU_IMAGE, MENU_DESCRIPTION, CALORIE, MENU_CATEGORY_CODE, MENU_COUNT)
VALUES (5001, '인절미', 3000,'r', 'MENU_05_5001.jpg', '부드러운 인절미과 달톰한꿀의 조합', 340, '05', 30);

INSERT INTO MENU (MENU_NO, MENU_NAME, PRICE, MENU_TYPE, MENU_IMAGE, MENU_DESCRIPTION, CALORIE, MENU_CATEGORY_CODE, MENU_COUNT)
VALUES (5002, '식혜', 2400, 'l', 'MENU_05_5002.jpg', '작게 썰어 말린 대추를올린 달콤한 식혜', 240, '05', 50);

INSERT INTO MENU (MENU_NO, MENU_NAME, PRICE, MENU_TYPE, MENU_IMAGE, MENU_DESCRIPTION, CALORIE, MENU_CATEGORY_CODE, MENU_COUNT)
VALUES (5003, '곳감수정과', 2500, 'a', 'MENU_05_5003.jpg', '잘말린 곳감을 작게 썰어 함께즐기는 새콤달콤한 곳감수정과', 200, '05', 30);

INSERT INTO MENU (MENU_NO, MENU_NAME, PRICE, MENU_TYPE, MENU_IMAGE, MENU_DESCRIPTION, CALORIE, MENU_CATEGORY_CODE, MENU_COUNT)
VALUES (5004, '양갱', 2500, 'a', 'MENU_05_5004', '다양한 맛을 즐기수 있는 전통적인 양갱', 250, '05', 60);

INSERT INTO MENU (MENU_NO, MENU_NAME, PRICE, MENU_TYPE, MENU_IMAGE, MENU_DESCRIPTION, CALORIE, MENU_CATEGORY_CODE, MENU_COUNT)
VALUES (5005, '오메기떡', 3000, 'a', 'MENU_05_5005.jpeg', '단백하고 다양한 토핑으로 같이 즐기수있는 전통적인 현대 떡', 150, '05', 20);
-------------------------------------------후식---------------------------------------------------------

- -------------------------------------------반찬류------------------------------------
INSERT INTO MENU (MENU_NO, MENU_NAME, PRICE, MENU_TYPE, MENU_IMAGE, MENU_DESCRIPTION, CALORIE, MENU_CATEGORY_CODE, MENU_COUNT)
VALUES (6001, '한우오이볶음', 4000,'r', 'MENU_06_6001.jpg', '단자스런운 한우고기랑 상큼한 오이의 만남', 140, '06', 80);

INSERT INTO MENU (MENU_NO, MENU_NAME, PRICE, MENU_TYPE, MENU_IMAGE, MENU_DESCRIPTION, CALORIE, MENU_CATEGORY_CODE, MENU_COUNT)
VALUES (6002, '장조림.', 3400, 'l', 'MENU_06_6002.jpg', '남녀노소 누구나 좋아하는 장조림', 110, '06', 50);

INSERT INTO MENU (MENU_NO, MENU_NAME, PRICE, MENU_TYPE, MENU_IMAGE, MENU_DESCRIPTION, CALORIE, MENU_CATEGORY_CODE, MENU_COUNT)
VALUES (6003, '오징어채', 2500, 'a', 'MENU_06_6003.jpg', '매콤하고 부드러운 국민반찬 오징어채', 210, '06', 40);

INSERT INTO MENU (MENU_NO, MENU_NAME, PRICE, MENU_TYPE, MENU_IMAGE, MENU_DESCRIPTION, CALORIE, MENU_CATEGORY_CODE, MENU_COUNT)
VALUES (6004, '계란말이', 2500, 'a', 'MENU_06_6004.jpg', '부드럽고 짭짭한 국민 밥반찬 계란말이', 250, '06', 60);

INSERT INTO MENU (MENU_NO, MENU_NAME, PRICE, MENU_TYPE, MENU_IMAGE, MENU_DESCRIPTION, CALORIE, MENU_CATEGORY_CODE, MENU_COUNT)
VALUES (6005, '느타리벗섯볶음', 3000, 'a', 'MENU_06_6005.jpg', '짭쫄한 밥반찬', 150, '06', 20);
-----------------------------------반찬류----------------------------------------------------

- -------------------------추천 메뉴------------------------------------------------------------
INSERT INTO SUGGEST_MENU (MENU_NO, SUGGEST_STATUS)
VALUES (1003, 'y');

INSERT INTO SUGGEST_MENU (MENU_NO, SUGGEST_STATUS)
VALUES (2008, 'y');

INSERT INTO SUGGEST_MENU (MENU_NO, SUGGEST_STATUS)
VALUES (3001, 'y');

INSERT INTO SUGGEST_MENU (MENU_NO, SUGGEST_STATUS)
VALUES (4002, 'y');

INSERT INTO SUGGEST_MENU (MENU_NO, SUGGEST_STATUS)
VALUES (5005, 'y');
--------------------------추천 메뉴------------------------------------------------------------

CREATE TABLE SUGGEST_MENU (
MENU_NO NUMBER NOT NULL,
SUGGEST_STATUS VARCHAR2(1) NOT NULL CHECK (SUGGEST_STATUS IN ('y','n')),
PRIMARY KEY (MENU_NO),
FOREIGN KEY (MENU_NO)
REFERENCES MENU (MENU_NO)
);

commit;
rollback;