INSERT INTO POST (POST_NO, POST_COUNT, TITLE, CONTENT, CREATION_DATE, MODIFICATION_DATE, DELETE_STATE, USERS_ID, CATEGORY_CODE)
VALUES 
(1, 100, 'Sample Title', 'Sample Content', TO_DATE('2024-11-01', 'YYYY-MM-DD'), TO_DATE('2024-11-01', 'YYYY-MM-DD'), 'N', 'imij0126', '01');

