INSERT INTO REPLY (POST_NO,REPLY_COMMENT,CREATION_DATE,DELETE_STATE)
VALUES (1,'응 안할거지롱~',SYSDATE,'N');

INSERT INTO REPLY (POST_NO,REPLY_COMMENT,CREATION_DATE,DELETE_STATE)
VALUES (2,'어쩔티비 저쩔티비',SYSDATE,'N');

INSERT INTO REPLY (POST_NO,REPLY_COMMENT,CREATION_DATE,DELETE_STATE)
VALUES (3,'베놈3 스토리 살인자가 칼들고 오는데 춤추고 있음',SYSDATE,'N');

INSERT INTO REPLY (POST_NO,REPLY_COMMENT,CREATION_DATE,DELETE_STATE)
VALUES (4,'뭘봐',SYSDATE,'N');

INSERT INTO REPLY (POST_NO,REPLY_COMMENT,CREATION_DATE,DELETE_STATE)
VALUES (5,'이제 쓰기도 귀찮다....',SYSDATE,'N');

SELECT R.REPLY_COMMENT, R.CREATION_DATE, U.USERS_NAME
FROM REPLY R
JOIN POST P ON R.POST_NO = P.POST_NO
JOIN USERS U ON P.USERS_ID = U.USERS_ID  -- USERS 테이블과 POST 테이블의 연결 조건 수정
WHERE P.POST_NO = 1;


